### ISSUE TITLE
lattigo template

### ISSUE THREAD

**Issue by osmenog** [Fherma-challenges/cifar-10#10]
Could you please publish a valid template for the lattigo project?

Things I need help with:
- Return input file should give about 10% accuracy (statistically), but I get 0. So the basic test fails. 
- How to pass rotation key indices? An example config.json would be very helpful.
- What should be in the Makefile?

**Comment by jqxue1999** [comment]
I have the same questions.

**Comment by g-s-m** [comment]
Hi @osmenog! Thank you for raising these questions. 
1. We just added a more detailed error message, so I hope you'll be able to find out a reason of failures for your solution 
2. Supporting rotation keys has been just added on the platform, you can use `indexes_for_rotation_key` parameter in the config.json file similar to the openfhe config. Galois keys will be serialized within the evaluation key set  and could be deserialized in your solution using the same template. 
3. Actually we are not using makefile during building a solution for lattigo projects, it was added to the template only for more convenient local development process.
