### ISSUE TITLE
OpenFHE EvalSum* Key Clarification

### ISSUE THREAD

**Issue by jkav77** [Fherma-challenges/cifar-10#3]
Hello, thanks for putting together a great challenge! 

I'm working with the University of Washington - Tacoma Privacy-Preserving Machine Learning research group to compete in this challenge and I just want to verify that `EvalSum*` keys were intentionally omitted from the challenge.

The reason I ask for clarification is this it makes the OpenFHE matrix operations unusable, i.e. `EvalInnerProduct`, `EvalSum`, `EvalSumRows` and `EvalSumColumns`.

**Comment by g-s-m** [comment]
Hi @jkav77  Thank you for raising this question, unfortunately currently we are not supported `EvalSum*` keys for any challenges on the FHERMA platform, but we are going to make it possible

**Comment by jkav77** [comment]
Thanks for the clarification. Our team is moving forward without needing those functions.
