### ISSUE TITLE
Dot Product rotation key indices

### ISSUE THREAD

**Issue by novamind** [Fherma-challenges/cifar-10#5]
Hello, thank you for challenging us so much!

I have some good results locally, but the tests on the server fail. I think this is because I used `cc.EvalSumKeyGen(keys.secretKey)` before exporting the Multiplication and Rotation keys. 

Currently, I run the inference locally using only two keys: key-eval-mult.bin and key-eval-rot.bin, serialized as follows:
```
cc.SerializeEvalMultKey("key-eval-mult.bin", BINARY)
cc.SerializeEvalAutomorphismKey("key-eval-rot.bin", BINARY)
```
However, without generating an `EvalSum`, I have to use a large list of indexes for the rotation key to perform the dot product operation. This approach significantly increases the RAM usage, but we are limited to 55GB of RAM.

Could we consider generating the EvalSum keys on the server side for this challenge?

**Comment by g-arakelov** [comment]
We will add the ability to generate EvalSum in the next platform update, and this feature will be available for new challenges, but unfortunately not for the current ones.
