### ISSUE TITLE
Decode(): The decryption failed because the approximation error is too high. Check the parameters.

### ISSUE THREAD

**Issue by jqxue1999** [Fherma-challenges/cifar-10#9]
![image](https://github.com/Fherma-challenges/cifar-10/assets/55708777/35219efd-d902-4dd9-a883-6004e077b000)

Hi, I meet this error when I test with the docker. But I don't know the reason for it. Which parameters should I pay attention to?

{
  "indexes_for_rotation_key": [
    1, 2, 32, 33, 34, 64, 65, 66, 1024, 8192, 4096, 2048, 512, 256, 128, 16, 8, 4, -1, -2, -3, -4, -5, -6, -7, -8, -9, 49152
  ],
  "mult_depth": 19,
  "ring_dimension": 131072,
  "scale_mod_size": 59,
  "first_mod_size": 60,
  "batch_size": 65536
}

I'm sure that the result level is smaller than the mult_depth

Here is my config.json file

**Comment by yellow123Nike** [comment]
I'm also having this issue, pls what is the reason？
